### ISSUE TITLE
Needing System.Net.Sockets to Reference System.Net.Sockets (.Net Core dll) instead of System.dll (.Net Framework)

### ISSUE THREAD

**Issue by vin2890** [ams-tschoening/ikvm-bin#3]
The issue I am having is one, I can not build the source code and modify this myself, second. I need this namespace to reference the .net core version. The reason being is in System.dll (.Net Framework), under System.Net.Sockets, There is no Enum for SocketOptionName.TcpKeepAliveInterval, I need to be able to set this as the socket option for linux to authenticate via Kerberos5. The windows socket options currently in OPENJDK.CORE, only work on windows and not linux. If i want to get this working in linux, I need to be able to set those options for the socket call. If i had a walk through to build IKVM, I could modify it myself, but have fallen short with the build, and therefore have been left with the option to modify the assembly. In looking into the contents of the assembly i came to realize that optionName was not available. Please get back with me when you have time!

**Comment by ams-tschoening** [comment]
Please post issues like this against [ikvm-revived](https://github.com/ikvm-revived/ikvm), as this repo is a only some storage  I need in somewhat private projects and NOT expected to discuss any source code changes.

Looking into your concrete issue, I suggest you create TWO different issues in ikvm-revived: One describing your build problems with concrete steps of what you have did and concrete error messages. The other one documenting the problem with the concrete socket options not supporting Linux, but available in .Net Core if I understand correctly.

At best, this will allow you to build IKVM on your own successfully and afterwards change source code to make it more compatible with .Net Core, at least in a private branch for only what you need to work. I did pretty much the same in the past, but won't be able to help too much.
